---
- name: Install nfs utilities
  yum:
    name: nfs-utils
    state: present

- name: Start rpcbind
  service:
    name: rpcbind
    state: started

- name: Create mountpoints before mounting
  file:
    path: "{{ item.value.mountpoint }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_dict: "{{ nfs_mounts }}"
  when: nfs_mounts is defined

- name: Mount paths
  mount:
    state: present
    fstype: "{{ item.value.type }}"
    opts: "{{ item.value.opt }}"
    src: "{{ item.value.src }}"
    path: "{{ item.value.mountpoint }}"
  with_dict: "{{ nfs_mounts }}"
  when: nfs_mounts is defined